'use client';
import { useState } from 'react';
import { Building2, Check, CreditCard, ExternalLink, Gift, Save, WalletCards } from 'lucide-react';

export function DonationSettings({ initial, canEdit }: { initial: any; canEdit: boolean }) {
  const normalizedInitial = { ...initial, donationHelloAssoEnabled: initial?.donationHelloAssoEnabled ?? Boolean(initial?.donationHelloAssoUrl) };
  const [form, setForm] = useState({ donationCardEnabled: false, donationStripeUrl: '', donationHelloAssoEnabled: false, donationHelloAssoUrl: '', donationTransferEnabled: false, donationIban: '', donationBic: '', donationAccountHolder: '', donationBankName: '', donationChequeEnabled: false, donationChequePayable: '', donationChequeAddress: '', leetchiEnabled: false, leetchiUrl: '', leetchiEmbedUrl: '', leetchiEmbedCode: '', leetchiCollectedEuros: '', leetchiGoalEuros: '', ...normalizedInitial });
  const [saved, setSaved] = useState(false);
  const set = (key: string, value: any) => setForm((current: any) => ({ ...current, [key]: value }));
  async function save() { const response = await fetch('/api/donation-settings', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); setSaved(response.ok); setTimeout(() => setSaved(false), 2000); }
  return <div className="card mb-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-extrabold"><WalletCards className="h-5 w-5 text-brand-600" /> Moyens de don affichés sur votre site</h2><p className="mt-1 text-sm text-gray-500">Ces informations sont privées dans l’administration. Seuls les moyens activés seront proposés aux visiteurs.</p></div>{saved && <span className="badge bg-green-100 text-green-700"><Check className="mr-1 h-3 w-3" /> Enregistré</span>}</div>
    <div className="mt-5 space-y-4">
      <section className="rounded-xl border border-gray-200 p-4"><label className="flex items-center gap-3 font-bold"><input type="checkbox" className="h-5 w-5" checked={form.donationCardEnabled} onChange={(e) => set('donationCardEnabled', e.target.checked)} /><CreditCard className="h-5 w-5" /> Carte bancaire / Stripe</label>{form.donationCardEnabled && <div className="mt-4"><label className="label">Lien de paiement Stripe</label><input className="input" type="url" value={form.donationStripeUrl} onChange={(e) => set('donationStripeUrl', e.target.value)} placeholder="https://buy.stripe.com/..." /></div>}</section>
      <section className="rounded-xl border border-gray-200 p-4"><label className="flex items-center gap-3 font-bold"><input type="checkbox" className="h-5 w-5" checked={form.donationHelloAssoEnabled} onChange={(e) => set('donationHelloAssoEnabled', e.target.checked)} /><ExternalLink className="h-5 w-5" /> HelloAsso</label>{form.donationHelloAssoEnabled && <div className="mt-4"><label className="label">Lien HelloAsso</label><input className="input" type="url" value={form.donationHelloAssoUrl} onChange={(e) => set('donationHelloAssoUrl', e.target.value)} placeholder="https://www.helloasso.com/..." /><p className="mt-2 text-xs text-gray-500">Ce lien sera automatiquement utilisé par le formulaire de dons du site.</p></div>}</section>
      <section className="rounded-xl border border-gray-200 p-4"><label className="flex items-center gap-3 font-bold"><input type="checkbox" className="h-5 w-5" checked={form.leetchiEnabled} onChange={(e) => set('leetchiEnabled', e.target.checked)} /><Gift className="h-5 w-5" /> Cagnotte Leetchi</label>{form.leetchiEnabled && <div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="sm:col-span-2"><label className="label">Lien de la cagnotte Leetchi</label><input className="input" type="url" value={form.leetchiUrl} onChange={(e) => set('leetchiUrl', e.target.value)} placeholder="https://www.leetchi.com/..." /><p className="mt-2 text-xs text-gray-500">Ce lien est obligatoire pour afficher le bloc Leetchi sur le site.</p></div><div><label className="label">Montant collecté affiché (€)</label><input className="input" type="number" min="0" value={form.leetchiCollectedEuros} onChange={(e) => set('leetchiCollectedEuros', e.target.value)} /></div><div><label className="label">Objectif de la cagnotte (€)</label><input className="input" type="number" min="0" value={form.leetchiGoalEuros} onChange={(e) => set('leetchiGoalEuros', e.target.value)} /></div><div className="sm:col-span-2"><label className="label">Lien ou iframe d’intégration Leetchi (optionnel)</label><input className="input" type="url" value={form.leetchiEmbedUrl} onChange={(e) => set('leetchiEmbedUrl', e.target.value)} placeholder="Lien d’intégration Leetchi si disponible" /><textarea className="input mt-2 min-h-24 font-mono text-xs" value={form.leetchiEmbedCode} onChange={(e) => set('leetchiEmbedCode', e.target.value)} placeholder="<iframe ...></iframe>" /><p className="mt-2 text-xs text-gray-500">Si Leetchi fournit un iframe, collez-le ici pour afficher la jauge Leetchi en direct.</p></div></div>}</section>
      <section className="rounded-xl border border-gray-200 p-4"><label className="flex items-center gap-3 font-bold"><input type="checkbox" className="h-5 w-5" checked={form.donationTransferEnabled} onChange={(e) => set('donationTransferEnabled', e.target.checked)} /><Building2 className="h-5 w-5" /> Virement bancaire</label>{form.donationTransferEnabled && <div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="sm:col-span-2"><label className="label">IBAN complet</label><input className="input font-mono" value={form.donationIban} onChange={(e) => set('donationIban', e.target.value)} /></div><div><label className="label">BIC / SWIFT</label><input className="input font-mono" value={form.donationBic} onChange={(e) => set('donationBic', e.target.value)} /></div><div><label className="label">Titulaire du compte</label><input className="input" value={form.donationAccountHolder} onChange={(e) => set('donationAccountHolder', e.target.value)} /></div><div><label className="label">Banque</label><input className="input" value={form.donationBankName} onChange={(e) => set('donationBankName', e.target.value)} /></div></div>}</section>
      <section className="rounded-xl border border-gray-200 p-4"><label className="flex items-center gap-3 font-bold"><input type="checkbox" className="h-5 w-5" checked={form.donationChequeEnabled} onChange={(e) => set('donationChequeEnabled', e.target.checked)} /><WalletCards className="h-5 w-5" /> Chèque</label>{form.donationChequeEnabled && <div className="mt-4 grid gap-3 sm:grid-cols-2"><div><label className="label">Ordre du chèque</label><input className="input" value={form.donationChequePayable} onChange={(e) => set('donationChequePayable', e.target.value)} /></div><div><label className="label">Adresse d’envoi</label><textarea className="input min-h-24" value={form.donationChequeAddress} onChange={(e) => set('donationChequeAddress', e.target.value)} /></div></div>}</section>
    </div>{canEdit && <button onClick={save} className="btn btn-primary mt-5"><Save className="h-4 w-4" /> Enregistrer et connecter au site</button>}</div>;
}
